langs("C")

cpp_header (
  name = "include",
  srcs = [
    "action_listener.h",
    "container_listener.h",
    "mouse_listener.h",
    "mouse_motion_listener.h",
    "mouse_wheel_listener.h",
  ],
  deps = [
    "//base:include",
    "//xpp/gfx:include",
  ],
)