langs("C")

cpp_binary (
  name = "example",
  srcs = [ "example.cc", ],
  deps = [
    "//xpp_inherit/ui:button",
    "//xpp_inherit/ui:include",
    "//xpp_inherit/ui:panel",
    "//xpp_inherit/ui:window",
  ],
)
